version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: devuser
  MYSQL_PASSWORD: 1234
  MYSQL_DATABASE: Conversiones
  REACT_APP_SERVER_PORT: 8000
  salt: saltTest

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/Conversor.sql:/docker-entrypoint-initdb.d/Conversor.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - mysql-db
  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start