-- MySQL Script generated by MySQL Workbench
-- Tue May 30 10:05:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Conversiones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Conversiones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Conversiones` DEFAULT CHARACTER SET utf8 ;
USE `Conversiones` ;

-- -----------------------------------------------------
-- Table `Conversiones`.`conversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conversiones`.`conversion` (
  `Con_id` INT NOT NULL AUTO_INCREMENT,
  `Con_fecha` DATE NULL,
  `Con_hora` TIME NULL,
  `Con_origen_uf` VARCHAR(45) NULL,
  `Con_fecha_uf` DATE NULL,
  `Con_destino_clp` INT NULL,
  `Con_Usu_id` INT NULL,
  `Con_uf_valor` VARCHAR(45) NULL,
  PRIMARY KEY (`Con_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conversiones`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conversiones`.`usuario` (
  `Usu_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `Usu_nombre` VARCHAR(45) NULL,
  `Usu_password` VARCHAR(100) NULL,
  `Usu_correo` VARCHAR(45) NULL,
  `Usu_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`Usu_id`))
ENGINE = InnoDB;

INSERT INTO `usuario` (`Usu_id`, `Usu_nombre`, `Usu_password`, `Usu_correo`, `Usu_tipo`) VALUES ('1', 'Felipe Aros', 'fbc71ce36cc20790f2eeed2197898e71', 'felipe@felipe.cl', 'user');

INSERT INTO `usuario` (`Usu_id`, `Usu_nombre`, `Usu_password`, `Usu_correo`, `Usu_tipo`) VALUES ('2', 'Diego Angulo', '81dc9bdb52d04dc20036dbd8313ed055', 'diego@diego.cl', 'admin');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
